import {
  arbitrumSepolia,
  avalancheFuji,
  baseSepolia,
  bitlayerTestnet,
  blastSepolia,
  botanixTestnet,
  bscTestnet,
  celoAlfajores,
  cronosTestnet,
  gnosisChiado,
  hashkeyTestnet,
  inkSepolia,
  lineaSepolia,
  mantleSepoliaTestnet,
  megaethTestnet,
  modeTestnet,
  monadTestnet,
  optimismSepolia,
  polygonAmoy,
  saigon,
  scrollSepolia,
  seiTestnet,
  sepolia,
  shibariumTestnet,
  soneiumMinato,
  sonicBlazeTestnet,
  unichainSepolia,
  xLayerTestnet,
  zircuitTestnet,
} from 'viem/chains';
import { config } from '../constants/config';
import { apechainCurtis, astarShibuya, coreTestnet } from './customViemChains';
import { networkTypes } from './networkTypes';

export const testnetNetworks = {
  arbitrumSepolia: {
    name: 'arbitrumSepolia',
    type: networkTypes.testnet,
    chainId: 421614,
    chainSelector: 421614,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: arbitrumSepolia,
  },
  baseSepolia: {
    name: 'baseSepolia',
    type: networkTypes.testnet,
    chainId: 84532,
    chainSelector: 84532,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: baseSepolia,
  },
  astarShibuya: {
    name: 'astarShibuya',
    type: networkTypes.testnet,
    chainId: 81,
    chainSelector: 81,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: astarShibuya,
  },
  roninSaigon: {
    name: 'roninSaigon',
    type: networkTypes.testnet,
    chainId: 2021,
    chainSelector: 2021,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: saigon,
  },
  megaethTestnet: {
    name: 'megaethTestnet',
    type: networkTypes.testnet,
    chainId: 6342,
    chainSelector: 6342,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: megaethTestnet,
  },
  sonicBlaze: {
    name: 'sonicBlaze',
    type: networkTypes.testnet,
    chainId: 57054,
    chainSelector: 57054,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: sonicBlazeTestnet,
  },
  monadTestnet: {
    name: 'monadTestnet',
    type: networkTypes.testnet,
    chainId: 10_143,
    chainSelector: 10_143,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: monadTestnet,
  },
  sepolia: {
    name: 'sepolia',
    type: networkTypes.testnet,
    chainId: 11155111,
    chainSelector: 11155111,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: sepolia,
  },
  lineaSepolia: {
    name: 'lineaSepolia',
    type: networkTypes.testnet,
    chainId: 59141,
    chainSelector: 59141,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: lineaSepolia,
  },
  bnbTestnet: {
    name: 'bnbTestnet',
    type: networkTypes.testnet,
    chainId: 97,
    chainSelector: 97,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: bscTestnet,
  },
  soneiumMinato: {
    name: 'soneiumMinato',
    type: networkTypes.testnet,
    chainId: 1946,
    chainSelector: 1946,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: soneiumMinato,
  },
  apechainCurtis: {
    name: 'apechainCurtis',
    type: networkTypes.testnet,
    chainId: 33111,
    chainSelector: 33111,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: apechainCurtis,
  },
  avalancheFuji: {
    name: 'avalancheFuji',
    type: networkTypes.testnet,
    chainId: 43113,
    chainSelector: 43113,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: avalancheFuji,
  },
  optimismSepolia: {
    name: 'optimismSepolia',
    type: networkTypes.testnet,
    chainId: 11155420,
    chainSelector: 11155420,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: optimismSepolia,
  },
  polygonAmoy: {
    name: 'polygonAmoy',
    type: networkTypes.testnet,
    chainId: 80002,
    chainSelector: 80002,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: polygonAmoy,
  },
  bitlayerTestnet: {
    name: 'bitlayerTestnet',
    type: networkTypes.testnet,
    chainId: 200810,
    chainSelector: 200810,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: bitlayerTestnet,
  },
  blastSepolia: {
    name: 'blastSepolia',
    type: networkTypes.testnet,
    chainId: 168587773,
    chainSelector: 1685877,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: blastSepolia,
  },
  botanixTestnet: {
    name: 'botanixTestnet',
    type: networkTypes.testnet,
    chainId: 3636,
    chainSelector: 3636,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: botanixTestnet,
  },
  celoAlfajores: {
    name: 'celoAlfajores',
    type: networkTypes.testnet,
    chainId: 44_787,
    chainSelector: 44_787,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: celoAlfajores,
  },
  coreTestnet: {
    name: 'coreTestnet',
    type: networkTypes.testnet,
    chainId: 1114,
    chainSelector: 1114,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: coreTestnet,
  },
  cronosTestnet: {
    name: 'cronosTestnet',
    type: networkTypes.testnet,
    chainId: 338,
    chainSelector: 338,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: cronosTestnet,
  },
  gnosisChiado: {
    name: 'gnosisChiado',
    type: networkTypes.testnet,
    chainId: 10_200,
    chainSelector: 10_200,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: gnosisChiado,
  },
  hashkeyTestnet: {
    name: 'hashkeyTestnet',
    type: networkTypes.testnet,
    chainId: 133,
    chainSelector: 133,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: hashkeyTestnet,
  },
  inkSepolia: {
    name: 'inkSepolia',
    type: networkTypes.testnet,
    chainId: 763373,
    chainSelector: 763373,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: inkSepolia,
  },
  mantleSepolia: {
    name: 'mantleSepolia',
    type: networkTypes.testnet,
    chainId: 5003,
    chainSelector: 5003,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: mantleSepoliaTestnet,
  },
  scrollSepolia: {
    name: 'scrollSepolia',
    type: networkTypes.testnet,
    chainId: 534351,
    chainSelector: 534351,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: scrollSepolia,
  },
  seiTestnet: {
    name: 'seiTestnet',
    type: networkTypes.testnet,
    chainId: 1328,
    chainSelector: 1328,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: seiTestnet,
  },
  shibariumPuppynet: {
    name: 'shibariumPuppynet',
    type: networkTypes.testnet,
    chainId: 157,
    chainSelector: 157,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: shibariumTestnet,
  },
  unichainSepolia: {
    name: 'unichainSepolia',
    type: networkTypes.testnet,
    chainId: 1301,
    chainSelector: 1301,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: unichainSepolia,
  },
  xlayerSepolia: {
    name: 'xlayerSepolia',
    type: networkTypes.testnet,
    chainId: 195,
    chainSelector: 195,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: xLayerTestnet,
  },
  zircuitTestnet: {
    name: 'zircuitTestnet',
    type: networkTypes.testnet,
    chainId: 48899,
    chainSelector: 48899,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: zircuitTestnet,
  },
  modeTestnet: {
    name: 'modeTestnet',
    type: networkTypes.testnet,
    chainId: 919,
    chainSelector: 919,
    confirmations: config.DEFAULT_BLOCK_CONFIRMATIONS,
    viemChain: modeTestnet,
  },
};

export type ConceroTestnetNetworkNames = keyof typeof testnetNetworks;
